### ISSUE TITLE
go demo is missing

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#120]
```sh
$ tea https://github.com/teaxyz/demos/blob/main/demo.go input.txt
tea: demo.go downloading
error: Uncaught (in promise) Error: 404: https://raw.githubusercontent.com/teaxyz/demos/main/demo.go
                throw new Error(`${rsp.status}: ${src}`);
                      ^
    at internal (file:///opt/tea.xyz/src/v0.11.4/src/hooks/useDownload.ts:75:23)
    at async Object.download (file:///opt/tea.xyz/src/v0.11.4/src/hooks/useDownload.ts:81:12)
    at async file:///opt/tea.xyz/src/v0.11.4/src/app.exec.ts:120:26
    at async abracadabra (file:///opt/tea.xyz/src/v0.11.4/src/app.exec.ts:115:18)
    at async exec (file:///opt/tea.xyz/src/v0.11.4/src/app.exec.ts:12:57)
    at async file:///opt/tea.xyz/src/v0.11.4/src/app.ts:29:9
```

**Comment by mxcl** [comment]
well we're trying to demonstrate `.go` files. But this will be a nice exe/md example once we process more than a single “target”

**Comment by mxcl** [comment]
Changed it to a working gist
