### ISSUE TITLE
running make on the whitepaper didn't respond as expected

### ISSUE THREAD

**Issue by RyanSinger** [teaxyz/cli#128]
```
➜  ~ cd white-paper 
➜  white-paper git:(main) make
pandoc \
	--number-sections \
	--output tea.white-paper.pdf \
	--metadata-file metadata.yml \
	--filter pandoc-crossref \
	--csl=tea.csl \
	--citeproc \
	white-paper.md
make: pandoc: No such file or directory
make: *** [tea.white-paper.pdf] Error 1
➜  white-paper git:(main) tea make
error: Uncaught (in promise) Error: 404-not-found: https://dist.tea.xyz/pandoc.org/darwin/aarch64/versions.txt
    if (!rsp.ok) throw new Error(`404-not-found: ${url}`) //FIXME
                       ^
    at Object.select (file:///opt/tea.xyz/src/v0.11.6/src/hooks/useInventory.ts:7:24)
    at async resolve (file:///opt/tea.xyz/src/v0.11.6/src/prefab/resolve.ts:18:29)
    at async install (file:///opt/tea.xyz/src/v0.11.6/src/app.exec.ts:63:17)
    at async exec (file:///opt/tea.xyz/src/v0.11.6/src/app.exec.ts:13:27)
    at async file:///opt/tea.xyz/src/v0.11.6/src/app.ts:29:9
➜  white-paper git:(main) tea .
error: Uncaught (in promise) Error: 404-not-found: https://dist.tea.xyz/pandoc.org/darwin/aarch64/versions.txt
    if (!rsp.ok) throw new Error(`404-not-found: ${url}`) //FIXME
                       ^
    at Object.select (file:///opt/tea.xyz/src/v0.11.6/src/hooks/useInventory.ts:7:24)
    at async resolve (file:///opt/tea.xyz/src/v0.11.6/src/prefab/resolve.ts:18:29)
    at async install (file:///opt/tea.xyz/src/v0.11.6/src/app.exec.ts:63:17)
    at async exec (file:///opt/tea.xyz/src/v0.11.6/src/app.exec.ts:13:27)
    at async file:///opt/tea.xyz/src/v0.11.6/src/app.ts:29:9
➜  white-paper git:(main) 

```

**Comment by mxcl** [comment]
Leaving open until I fix this better.

**Comment by nscooling** [comment]
I'm getting this, slightly different, error:
```
white-paper git:(main) tea -S
tea: pantries sync’d ⎷
tea: installed: ~/.tea/pandoc.org/v2.19.2
tea: installed: ~/.tea/pandoc.org/crossref/v0.3.13
tea: installed: ~/.tea/gnome.org/librsvg/v2.55.1
tea: installed: ~/.tea/gnu.org/make/v4.3.0
tea: installed: ~/.tea/sourceware.org/libffi/v3.4.3
tea: installed: ~/.tea/sourceware.org/bzip2/v1.0.8
tea: installed: ~/.tea/pcre.org/v8.45.0
tea: installed: ~/.tea/libexpat.github.io/v2.5.0
tea: installed: ~/.tea/libpng.org/v1.6.35
tea: installed: ~/.tea/pixman.org/v0.40.0
tea: installed: ~/.tea/freetype.org/v2.12.1
tea: installed: ~/.tea/gnome.org/glib/v2.72.4
tea: installed: ~/.tea/freedesktop.org/fontconfig/v2.14.0
tea: installed: ~/.tea/cairographics.org/v1.16.0
tea: installed: ~/.tea/unicode.org/v71.1.0
tea: installed: ~/.tea/harfbuzz.org/v5.3.1
tea: installed: ~/.tea/gnu.org/fribidi/v1.0.12
tea: installed: ~/.tea/ijg.org/v9.5.0
tea: installed: ~/.tea/freedesktop.org/shared-mime-info/v2.2.0
tea: installed: ~/.tea/gnu.org/gmp/v6.2.1
tea: installed: ~/.tea/gnome.org/pango/v1.50.9
tea: installed: ~/.tea/gnome.org/gdk-pixbuf/v2.42.8
this is a temporary shell containing the following packages:
gnome.org/libxml2@2.10.3, zlib.net@1.2.13, gnu.org/gettext@0.21.1, tea.xyz/gx/cc@0.1.1, pandoc.org@2.19.2, pandoc.org/crossref@0.3.13, gnome.org/librsvg@2.55.1, gnu.org/make@4.3.0, sourceware.org/libffi@3.4.3, sourceware.org/bzip2@1.0.8, pcre.org@8.45.0, libexpat.github.io@2.5.0, libpng.org@1.6.35, pixman.org@0.40.0, freetype.org@2.12.1, gnome.org/glib@2.72.4, freedesktop.org/fontconfig@2.14.0, cairographics.org@1.16.0, unicode.org@71.1.0, harfbuzz.org@5.3.1, gnu.org/fribidi@1.0.12, ijg.org@9.5.0, freedesktop.org/shared-mime-info@2.2.0, gnu.org/gmp@6.2.1, gnome.org/pango@1.50.9, gnome.org/gdk-pixbuf@2.42.8
when done type: `exit'
tea ~/test-time/white-paper make
pandoc \
--number-sections \
--output tea.white-paper.pdf \
--metadata-file metadata.yml \
--filter pandoc-crossref \
--csl=tea.csl \
--citeproc \
white-paper.md
pandoc: pdflatex: createProcess: posix_spawnp: illegal operation (Inappropriate ioctl for device)
make: *** [Makefile:10: tea.white-paper.pdf] Error 1
```

M1 MBP Version 13.0.1 (22A400)

**Comment by jhheider** [comment]
At present, this process still requires texlive ([ubuntu](https://github.com/teaxyz/white-paper/blob/1d18ed985194a054085560b56cac3a24514a96a9/.github/workflows/make.yml#L25-L31)) or mactex on macOS. Packaging texlive promises to be challenging, due to the number of dependencies, which is why we haven't done it yet. So, as far as building the white-paper today, those solutions will work. Obviously, if you're excited to package texlive and its dependencies, we welcome all submissions. :)

**Comment by nscooling** [comment]
Okay, that is now fine - just some font issues, but working okay. 

Thanks
