### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by benjaminbours** [teaxyz/cli#138]
```
sh <(curl tea.xyz) https://github.com/teaxyz/cli
```

Is returning

```
error: http (spilt-tea-404)
400: https://raw.githubusercontent.com/teaxyz/cli
```

While in the `README.md` we can see [this written](https://github.com/teaxyz/cli#executable-markdown).

**Comment by mxcl** [comment]
Though this particular usage would be hilarious since it will essentially run `sh <(curl tea.xyz)` after cloning tea/cli :D

**Comment by magnusviri** [comment]
I'm not sure if executable markdown works yet. If it's supposed to, I get this error.

```
> tea https://github.com/magnusviri/tea-notes/blob/main/README.md
tea: README.md downloading

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Anot-found%3Asrcroot

----------------------------------------------------->> attachment begin
Error: not-found:srcroot
    at file:///opt/tea.xyz/src/v0.13.0/src/hooks/useVirtualEnv.ts:34:15
    at useVirtualEnv (file:///opt/tea.xyz/src/v0.13.0/src/hooks/useVirtualEnv.ts:35:7)
    at abracadabra (file:///opt/tea.xyz/src/v0.13.0/src/app.exec.ts:163:25)
    at async exec (file:///opt/tea.xyz/src/v0.13.0/src/app.exec.ts:12:72)
    at async file:///opt/tea.xyz/src/v0.13.0/src/app.ts:30:9
<<------------------------------------------------------ attachment ends
```

**Comment by magnusviri** [comment]
I have been trying to build a package and I noticed this output. The TEA_PREFIX is certainly set ("/opt/tea"), but the PATH isn't getting the correct prefix ("/opt/tea.xyz").

```
+ export TEA_PREFIX=/opt/tea
+ TEA_PREFIX=/opt/tea
+ export MACOSX_DEPLOYMENT_TARGET=11.0
+ MACOSX_DEPLOYMENT_TARGET=11.0
+ export PATH=/opt/tea.xyz/var/pantry/scripts/brewkit:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
+ PATH=/opt/tea.xyz/var/pantry/scripts/brewkit:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
```

**Comment by magnusviri** [comment]
I just figured out why the paths are the way they are. I submitted [another issue about it](https://github.com/teaxyz/pantry.core/issues/36). I think it's unrelated to this issue.

**Comment by mxcl** [comment]
These examples have been removed. We may still add the feature where you can run commands against a repo. Maybe. Feels a little out of scope.
