### ISSUE TITLE
Error split tea: panic:invalid absolute path: 

### ISSUE THREAD

**Issue by maxsz** [teaxyz/cli#144]
On macOS 13 arm64, zsh, node version v16.18.0 I get the following error when trying to run the example directly after installing (`sh <(curl tea.xyz)`). It told me that I have to report the bug, so here you go 😆 Do you have any hint on how I can debug this? Thanks!

```
❯ tea +gnu.org/wget wget -qO- tea.xyz/white-paper | tea +charm.sh/glow glow -
tea: installed: ~/.tea/openssl.org/v1.1.118
tea: installed: ~/.tea/gnu.org/wget/v1.21.3

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ainvalid+absolute+path%3A+.

----------------------------------------------------->> attachment begin
Error: invalid absolute path: .
    at new Path (file:///opt/tea.xyz/src/v0.11.13/src/vendor/Path.ts:38:19)
    at find_tea (file:///opt/tea.xyz/src/v0.11.13/src/hooks/useShellEnv.ts:177:22)
    at useShellEnv (file:///opt/tea.xyz/src/v0.11.13/src/hooks/useShellEnv.ts:89:29)
    at exec (file:///opt/tea.xyz/src/v0.11.13/src/app.exec.ts:18:32)
    at async file:///opt/tea.xyz/src/v0.11.13/src/app.ts:29:9
<<------------------------------------------------------ attachment ends
tea: installed: ~/.tea/charm.sh/glow/v1.4.1

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ainvalid+absolute+path%3A+.

----------------------------------------------------->> attachment begin
Error: invalid absolute path: .
    at new Path (file:///opt/tea.xyz/src/v0.11.13/src/vendor/Path.ts:38:19)
    at find_tea (file:///opt/tea.xyz/src/v0.11.13/src/hooks/useShellEnv.ts:177:22)
    at useShellEnv (file:///opt/tea.xyz/src/v0.11.13/src/hooks/useShellEnv.ts:89:29)
    at exec (file:///opt/tea.xyz/src/v0.11.13/src/app.exec.ts:18:32)
    at async file:///opt/tea.xyz/src/v0.11.13/src/app.ts:29:9
<<------------------------------------------------------ attachment ends
```

**Comment by mxcl** [comment]
thank you! It appears you have `.` in your `PATH`. Correct?

**Comment by mxcl** [comment]
Fix for that coming up. You can watch the build in @teaxyz/pantry.core/actions (not there yet). Once built you can update with `sh <(curl tea.xyz)`

Please close if fixed!

**Comment by maxsz** [comment]
Indeed, I do! Working now, thanks!
