### ISSUE TITLE
Explicit package versions don't constrain existing installs

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#156]
How do we specify a specific version of a package? I can't find this documented anywhere. I tried a few things and I think the character is "~" because when I use that it at least generates an error (my other guess, "@", doesn't generate an error).

```
> tea +python.org~v3.10 python
error: Uncaught Error: invalid semver range: ~v3.10
                if (!match) throw new Error(`invalid semver range: ${input}`);
                                  ^
    at file:///opt/tea.xyz/src/v0.13.0/src/utils/semver.ts:153:35
    at Array.map (<anonymous>)
    at new Range (file:///opt/tea.xyz/src/v0.13.0/src/utils/semver.ts:106:56)
    at Module.parse (file:///opt/tea.xyz/src/v0.13.0/src/utils/pkg.ts:32:28)
    at useArgs (file:///opt/tea.xyz/src/v0.13.0/src/hooks/useFlags.ts:51:30)
    at file:///opt/tea.xyz/src/v0.13.0/src/app.ts:11:44
```

However, it doesn't work either.

```
> tea +python.org~3.10 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea --version
tea 0.13.0
```

**Comment by jhheider** [comment]
For a specific minor, you have a few options in semver: (~|^)3.10.0 should work, (=|@)3.10.8 (just checked; that's the 3.10 version we have built at present) should work, and '>=3.10.0 <3.11.0' should work.

I believe the issue you hit is that ~3.10 means '>=3.10.0 <4', while ~3.10.0 means '>=3.10.0 <3.11.0'.

**Comment by magnusviri** [comment]
I think I'm missing something because no matter what I do, it runs python 3.11.

```
> tea +python.org~3.10.0 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org~3.10 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org^3.10.0 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org^3.10 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org=3.10 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org=3.10.0 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org=3.10.8 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
> tea +python.org@3.10.8 python
Python 3.11.0 (main, Oct 29 2022, 23:30:44) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by jhheider** [comment]
Confirmed, and definitely not as intended.

**Comment by mxcl** [comment]
lol what a farce, sorry, fixing.

fyi:

```
$ tea +python.org@3.10 python   # => 3.10.0

$ tea +python.org^3.10 python    # => >3.10.0<4

$ tea +python.org~3.10 python    # => >3.10.0<3.11
```

per the semver.org spec are what we support.

**Comment by mxcl** [comment]
k good news: this is because python depends on python and is not generally a bug:

```sh
tea +deno.land@1.26.2 deno --version
tea: installed: ~/.tea/deno.land/v1.26.2
deno 1.26.2 (release, aarch64-apple-darwin)
v8 10.7.193.16
typescript 4.8.3
```

**Comment by mxcl** [comment]
bug is in `semver.intersect`, notably we had to write this function ourselves since neither Deno of Node’s semver provide it.

Was the main justification for doing our own semver lib (among other reasons)

**Comment by magnusviri** [comment]
I think this is fixed so I'll close this.
