### ISSUE TITLE
Problem with tea fetching package graph; no pantry error; `tea --sync` doesn't help 

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#194]
I ran into this problem with packaging 

Setup + fresh install of `tea`
```
$ ls 
cli
pantry.core
pantry.extra
```

Output:
```
$ TEA_PANTRY_PATH="$PWD/pantry.extra" pantry.core/scripts/build.ts just.systems
tea: resolving package graph
Error: no pantry: run `tea --sync`
    at entry (file:///opt/tea.xyz/src/v0.13.9/src/hooks/usePantry.ts:150:34)
    at Object.getCompanions (file:///opt/tea.xyz/src/v0.13.9/src/hooks/usePantry.ts:139:23)
    at install (file:///opt/tea.xyz/src/v0.13.9/src/app.exec.ts:351:39)
    at exec (file:///opt/tea.xyz/src/v0.13.9/src/app.exec.ts:178:46)
    at async default (file:///opt/tea.xyz/src/v0.13.9/src/app.exec.ts:24:9)
    at async file:///opt/tea.xyz/src/v0.13.9/src/app.ts:31:9
error: not-found: pantry (spilt-tea-005)
no pantry: run `tea --sync`
```

`tea --sync` doesn't change the output

I'm on an Intel Mac

**Comment by mfts** [comment]
Again fresh install of `tea@0.13.11`; same error

```
$ TEA_PANTRY_PATH="$PWD/pantry.extra" pantry.core/scripts/build.ts just.systems
tea: installed: ~/.tea/deno.land/v1.28.1
tea: installed: ~/.tea/gnu.org/tar/v1.34.0
tea: installed: ~/.tea/tukaani.org/xz/v5.2.7
tea: installed: ~/.tea/sourceware.org/bzip2/v1.0.8
error: Uncaught (in promise) Error: no pantry: run `tea --sync`
    if (!dir.exists()) throw new TeaError('not-found: pantry', { path: prefix })
                             ^
    at entry (file:///Users/mfts/Developer/tea2/pantry.core/src/hooks/usePantry.ts:171:30)
    at Object.getDeps (file:///Users/mfts/Developer/tea2/pantry.core/src/hooks/usePantry.ts:53:21)
    at get (file:///Users/mfts/Developer/tea2/pantry.core/src/prefab/hydrate.ts:33:52)
    at ascend (file:///Users/mfts/Developer/tea2/pantry.core/src/prefab/hydrate.ts:62:31)
    at go (file:///Users/mfts/Developer/tea2/pantry.core/src/prefab/hydrate.ts:92:11)
    at hydrate (file:///Users/mfts/Developer/tea2/pantry.core/src/prefab/hydrate.ts:99:11)
    at file:///Users/mfts/Developer/tea2/pantry.core/scripts/build.ts:36:21
```

**Comment by mxcl** [comment]
worksforme

**Comment by mxcl** [comment]
yeah this line of code no longer exists: `if (!dir.exists()) throw new TeaError('not-found: pantry', { path: prefix })`

so you aren't running the latest version somehow

**Comment by mfts** [comment]
Yes PR #195 fixes the issue, updated my comment above to make it clear that I hadn't updated `tea/cli` to latest remote commit

**Comment by mxcl** [comment]
edit: no turns out is was because our scripts use the sources in tea/cli and they hadn't been updated.
