### ISSUE TITLE
Tea reports an error when it's user error

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#224]
```
> tea -X python asdf
/opt/tea/python.org/v3.11.0/bin/python: can't open file '/Users/u0076374/Dropbox/Work/jctl/asdf': [Errno 2] No such file or directory

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!
...
```

This error has nothing to do with tea, so it shouldn't own the error.

**Comment by mxcl** [comment]
yeah I deliberately made most errors ask you to report the bug so we could figure out which ones are and aren't our fault. So indeed, this one should be changed.

**Comment by magnusviri** [comment]
If I specify the package then it doesn't throw an error, but if I use -X or nothing, it does.

```
> tea +stedolan.github.io/jq jq
jq - commandline JSON processor [version 1.6]
...
For a listing of options, use jq --help.


> tea -X jq
jq - commandline JSON processor [version 1.6]

Usage:	/opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq [options] <jq filter> [file...]
...
For a listing of options, use /opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq --help.

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Acmd+failed%3A+2%3A+%2Fopt%2Ftea%2Fstedolan.github.io%2Fjq%2Fv1.6.0%2Fbin%2Fjq

----------------------------------------------------->> attachment begin
Error: cmd failed: 2: /opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq
    at run (file:///opt/tea.xyz/src/v0.16.0/src/utils/index.ts:194:34)
    at async X (file:///opt/tea.xyz/src/v0.16.0/src/app.X.ts:36:5)
    at async file:///opt/tea.xyz/src/v0.16.0/src/app.ts:34:9
<<------------------------------------------------------- attachment end


> tea jq
jq - commandline JSON processor [version 1.6]
...
For a listing of options, use /opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq --help.

panic: split tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Acmd+failed%3A+2%3A+%2Fopt%2Ftea%2Fstedolan.github.io%2Fjq%2Fv1.6.0%2Fbin%2Fjq

----------------------------------------------------->> attachment begin
Error: cmd failed: 2: /opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq
    at run (file:///opt/tea.xyz/src/v0.16.0/src/utils/index.ts:194:34)
    at async X (file:///opt/tea.xyz/src/v0.16.0/src/app.X.ts:36:5)
    at async file:///opt/tea.xyz/src/v0.16.0/src/app.ts:34:9
<<------------------------------------------------------- attachment end
```
