### ISSUE TITLE
panic:invalid semver range: 2.4.9

### ISSUE THREAD

**Issue by Lunchb0ne** [teaxyz/cli#272]
Getting this panic with tea when I try to go to the white-paper dir and execute `tea --env --dump`

```
Error: invalid semver range: 2.4.9
    at err (file:///opt/tea.xyz/src/v0.17.0/src/utils/semver.ts:102:29)
    at file:///opt/tea.xyz/src/v0.17.0/src/utils/semver.ts:160:23
    at Array.map (<anonymous>)
    at new Range (file:///opt/tea.xyz/src/v0.17.0/src/utils/semver.ts:103:56)
    at validatePackageRequirement (file:///opt/tea.xyz/src/v0.17.0/src/utils/hacks.ts:30:18)
    at parse_pkgs_node (file:///opt/tea.xyz/src/v0.17.0/src/hooks/usePantry.ts:59:25)
    at Object.getDeps (file:///opt/tea.xyz/src/v0.17.0/src/hooks/usePantry.ts:48:16)
    at async ascend (file:///opt/tea.xyz/src/v0.17.0/src/prefab/hydrate.ts:30:32)
    at async ascend (file:///opt/tea.xyz/src/v0.17.0/src/prefab/hydrate.ts:51:25)
    at async go (file:///opt/tea.xyz/src/v0.17.0/src/prefab/hydrate.ts:59:9)
```

Is there any more information that I can get about this? Is there a place where tea stores dir-related metadata?

**Comment by reza092025** [comment]
I hope your project can be successful and successfful in the future, I also hope the community can grow even bigger than now
