### ISSUE TITLE
panic:Is a directory (os error 21)

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#302]
<img width="972" alt="Screenshot 2023-01-15 at 1 37 13 PM" src="https://user-images.githubusercontent.com/7913978/212524682-071cf297-e925-463f-9d81-895b59d1aa18.png">

OS: docker ubuntu:20.04

**Comment by getneil** [comment]
----------------------------------------------------->> attachment begin
Error: Is a directory (os error 21)
    at async read (deno:runtime/js/12_io.js:106:19)
    at async BufReader.#fill (https://deno.land/std@0.156.0/io/buffer.ts:265:24)
    at async BufReader.readSlice (https://deno.land/std@0.156.0/io/buffer.ts:516:17)
    at async BufReader.readLine (https://deno.land/std@0.156.0/io/buffer.ts:419:20)
    at async readLines (https://deno.land/std@0.156.0/io/buffer.ts:834:21)
    at async readYAMLFrontMatter (file:///opt/tea.xyz/src/v0.19.1/src/hooks/usePackageYAML.ts:83:22)
    at async usePackageYAMLFrontMatter (file:///opt/tea.xyz/src/v0.19.1/src/hooks/usePackageYAML.ts:30:18)
    at async default (file:///opt/tea.xyz/src/v0.19.1/src/hooks/useExec.ts:26:22)
    at async file:///opt/tea.xyz/src/v0.19.1/src/app.ts:35:47
<<----------------------------------------------------- attachment end

**Comment by jhheider** [comment]
Likely due to `md/exe` being removed from the cli. "The author" [suggests alternative runners](https://github.com/teaxyz/cli#what-happened-to-executable-markdown).

**Comment by mxcl** [comment]
Yeah looks like we're trying to open a directory. I don’t know what the tea-call line was (though that would be useful debug output) so can't help further.

Neil if you could stop linking publicly in our most visible repo to our secret gui project I would appreciate it.

**Comment by mxcl** [comment]
K 0.19.2 fixes trying to open directories but likely you will get another error due to removing exe/md (for which I apologize that we made you use it).
