### ISSUE TITLE
panic:Is a directory (os error 21)

### ISSUE THREAD

**Issue by tnxz** [teaxyz/cli#305]
```tea foo``` panics when there Is ```foo``` directory in the current working directory.
```
Error: Is a directory (os error 21)
    at async read (deno:runtime/js/12_io.js:106:19)
    at async BufReader.#fill (https://deno.land/std@0.156.0/io/buffer.ts:265:24)
    at async BufReader.readSlice (https://deno.land/std@0.156.0/io/buffer.ts:516:17)
    at async BufReader.readLine (https://deno.land/std@0.156.0/io/buffer.ts:419:20)
    at async readLines (https://deno.land/std@0.156.0/io/buffer.ts:834:21)
    at async readYAMLFrontMatter (file:///opt/tea.xyz/src/v0.19.1/src/hooks/usePackageYAML.ts:83:22)
    at async usePackageYAMLFrontMatter (file:///opt/tea.xyz/src/v0.19.1/src/hooks/usePackageYAML.ts:30:18)
    at async default (file:///opt/tea.xyz/src/v0.19.1/src/hooks/useExec.ts:26:22)
    at async file:///opt/tea.xyz/src/v0.19.1/src/app.ts:35:47
```

**Comment by getneil** [comment]
ff

**Comment by tnxz** [comment]
#303 seems to have fixed this in the latest version
