### ISSUE TITLE
panic:FORK BOMB KILL SWITCH ACTIVATED

### ISSUE THREAD

**Issue by tnxz** [teaxyz/cli#308]
```
Error: FORK BOMB KILL SWITCH ACTIVATED
    at default (file:///opt/tea.xyz/src/v0.19.1/src/app.exec.ts:10:28)
    at file:///opt/tea.xyz/src/v0.19.1/src/app.ts:54:27
```

**Comment by mxcl** [comment]
lol glad I added this kill switch. Closing in favor of #306
