### ISSUE TITLE
shell detection failure: SHELL=/bin/bash

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#336]
Mostly pristine `debian:buster-slim` linux/amd64:
```sh
root@987de5b63481:/# tea --magic

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Aunsupported+shell

----------------------------------------------------->> attachment begin
Error: unsupported shell
    at default (file:///opt/tea.xyz/src/v0.21.0/src/app.magic.ts:60:19)
    at file:///opt/tea.xyz/src/v0.21.0/src/app.ts:109:25
<<----------------------------------------------------- attachment end
root@987de5b63481:/# echo $SHELL
/bin/bash
root@987de5b63481:/# SHELL=/bin/bash tea --magic
cd() {
  builtin cd "$@" || return
  if [ "$OLDPWD" != "$PWD" ]; then
    source <("/root/.tea/tea.xyz/v0.21.0/bin"/tea +tea.xyz/magic -Esk --chaste env)
  fi
}

# if the user put tea in eg. /usr/local/bin then don’t pollute their PATH
if ! tea --prefix 2>&1 >/dev/null; then
  export PATH="/root/.tea/tea.xyz/v0.21.0/bin:$PATH"
fi

function command_not_found_handle {
  "/root/.tea/tea.xyz/v0.21.0/bin"/tea -- $*
}
root@987de5b63481:/# export SHELL
root@987de5b63481:/# tea --magic
cd() {
  builtin cd "$@" || return
  if [ "$OLDPWD" != "$PWD" ]; then
    source <("/root/.tea/tea.xyz/v0.21.0/bin"/tea +tea.xyz/magic -Esk --chaste env)
  fi
}

# if the user put tea in eg. /usr/local/bin then don’t pollute their PATH
if ! tea --prefix 2>&1 >/dev/null; then
  export PATH="/root/.tea/tea.xyz/v0.21.0/bin:$PATH"
fi

function command_not_found_handle {
  "/root/.tea/tea.xyz/v0.21.0/bin"/tea -- $*
}
```

Very odd. SHELL isn't exported by default. I wonder if there's a fix for that.

**Comment by mxcl** [comment]
I added `tea --magic=bash` as an option (for unrelated reasons).

We could default to bash potentially rather than error.

We could run `sh` and see what we get using `ps -hp`

**Comment by mxcl** [comment]
I think the best bet is explicitly specifying it, which we now do.
