### ISSUE TITLE
panic:the stream contains non-printable characters at line 8, column 1:    ^=^C^DaAambBdbdcdoeEeneqfFgegogt ...     ^

### ISSUE THREAD

**Issue by OutOfBedlam** [teaxyz/cli#345]
YAMLError: the stream contains non-printable characters at line 8, column 1:
    ^=^C^DaAambBdbdcdoeEeneqfFgegogt ...
    ^
    at generateError (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:88:12)
    at throwError (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:91:11)
    at captureSegment (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:154:20)
    at readPlainScalar (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:331:13)
    at composeNode (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:944:28)
    at readBlockMapping (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:706:20)
    at composeNode (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:934:84)
    at readDocument (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:1055:5)
    at loadDocuments (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:1093:9)
    at load (https://deno.land/std@0.173.0/encoding/_yaml/loader/loader.ts:1112:23)

**Comment by jhheider** [comment]
What command was being run?

**Comment by mxcl** [comment]
The YAML must have been corrupted somehow. But yes, what command was run?
