### ISSUE TITLE
Unfriendly error message when trying to use a version that doesn't exist

### ISSUE THREAD

**Issue by lino-levan** [teaxyz/cli#353]
Here I was trying to use a deno version a few updates back but accidentally referenced a version that never existed. This probably should not cause tea to panic.

```bash
$ deno~1.29.4 --version
resolving package graph
{
  project: "deno.land",
  path: ~/.tea/tea.xyz/var/pantry/projects/deno.land/package.yml,
  constraint: ~1.29.4,
  shebang: "deno",
  version: undefined
}

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ano+bottle+available

----------------------------------------------------->> attachment begin
Error: no bottle available
    at resolve (file:///private/tmp/tea-cli-20230128-57004-vtaatg/tea-0.21.4/src/prefab/resolve.ts:30:23)
    at async install (file:///private/tmp/tea-cli-20230128-57004-vtaatg/tea-0.21.4/src/hooks/useExec.ts:88:38)
    at async default (file:///private/tmp/tea-cli-20230128-57004-vtaatg/tea-0.21.4/src/hooks/useExec.ts:65:25)
    at async file:///private/tmp/tea-cli-20230128-57004-vtaatg/tea-0.21.4/src/app.ts:37:63
<<----------------------------------------------------- attachment end
```

**Comment by mxcl** [comment]
lol, will fix.

We default everything to panic, this way we get the bug reports and fix it. However, sorry for the way it sounds :D

**Comment by mxcl** [comment]
https://github.com/teaxyz/cli/pull/355

**Comment by lino-levan** [comment]
Nice!
