### ISSUE TITLE
`tea bundle install` is broken

### ISSUE THREAD

**Issue by davdroman** [teaxyz/cli#374]
Somehow this used to work for me a few weeks ago but now it doesn't. Not sure what could've happened in between:

```sh
$ tea bundle install
/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems.rb:282:in `activate_bin_path'
	from /Users/davdroman/.tea/rubygems.org/v3.4.6/bin/bundle:25:in `<main>'
```

Any idea what could be causing it? I tried `rm -rf /Users/davdroman/.tea/rubygems.org` and `rm -rf /Users/davdroman/.tea/ruby-lang.org` but it hasn't made a difference.

**Comment by davdroman** [comment]
If I try to install bundler via tea:

```sh
$ tea gem install bundle
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby or use non-HTTPS sources (Gem::Exception)
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request.rb:47:in `configure_connection_for_https'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request/https_pool.rb:6:in `setup_connection'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request/http_pool.rb:39:in `make_connection'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request/http_pool.rb:20:in `checkout'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request.rb:129:in `connection_for'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request.rb:188:in `perform_request'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/request.rb:154:in `fetch'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/remote_fetcher.rb:309:in `request'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/remote_fetcher.rb:209:in `fetch_http'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/remote_fetcher.rb:248:in `fetch_path'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/source.rb:88:in `dependency_resolver_set'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/source_list.rb:94:in `each'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/source_list.rb:94:in `each_source'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/resolver/best_set.rb:28:in `find_all'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/resolver/installer_set.rb:170:in `find_all'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/resolver/installer_set.rb:61:in `add_always_install'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:205:in `install_gem'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:191:in `process_args'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
	/Users/davdroman/.tea/ruby-lang.org/v3.2.1/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
	/Users/davdroman/.tea/rubygems.org/v3.4.6/bin/gem:10:in `<main>'
```

**Comment by mxcl** [comment]
Hmm can confirm. Will look into it this weekend. Sorry for the hassle :(

**Comment by davdroman** [comment]
No worries. Thanks for the prompt response :)

**Comment by mxcl** [comment]
Hopefully fixed:

```
rm -rf ~/.tea/ruby*/v* && tea --sync +rubygems.org
```

For me it works:

```sh
$ tea gem install bundle
Fetching bundle-0.0.1.gem
WARNING:  You don't have /Users/mxcl/.local/bin in your PATH,
	  gem executables will not run.
Successfully installed bundle-0.0.1
Parsing documentation for bundle-0.0.1
Done installing documentation for bundle after 1 seconds
1 gem installed
```

**Comment by davdroman** [comment]
@mxcl hooray! 🎉 works for me too. What should I do about `~/.local/bin`? Is it wise to add it to my PATH?

**Comment by mxcl** [comment]
> What should I do about ~/.local/bin? Is it wise to add it to my PATH?

Next tea/cli release the magic will add this PATH for you as I intend to have it be a general place (per freedesktop.org spec) that tools like `gem` put their binaries.

**Comment by davdroman** [comment]
Amazing. Thank you for tracking this down and for all your hard work :)

**Comment by mxcl** [comment]
Thanks for your report and for generally being a passionate early adopter, it's people like you who will be instrumental in our ascent as a useful developer tool ☺️
