### ISSUE TITLE
Misspelled package names in `package.yml` throws imprecise error for `pkg build`

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#390]
In package.yml file, if one misspells a package name like 

```

...
build: 
   dependencies: 
      gnome.org/libxlst: '*' # incorrect
      gnome.org/libxslt: '*' # correct
...
```

The error output when running `pkg build pkg-name.org` is

```sh
error: Uncaught (in promise) Error:     https://github.com/teaxyz/pantry.zero#contributing

  throw new TeaError('not-found: pantry: package.yml', {project}, )
        ^
    at entry (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/hooks/usePantry.ts:221:9)
    at Object.getDeps (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/hooks/usePantry.ts:60:21)
    at file:///Users/mfts/dev/tea/pantry.extra/tea.out/tea.xyz/brewkit/v0.3.1/libexec/sort.ts:31:29
    at ascend (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/prefab/hydrate.ts:62:31)
    at ascend (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/prefab/hydrate.ts:87:19)
    at async go (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/prefab/hydrate.ts:92:5)
    at async hydrate (https://raw.githubusercontent.com/teaxyz/cli/v0.23/src/prefab/hydrate.ts:99:5)
    at async file:///Users/mfts/dev/tea/pantry.extra/tea.out/tea.xyz/brewkit/v0.3.1/libexec/sort.ts:30:13
```

## Suggestion
A helpful error message would to tell me which package cannot be found.

**Comment by lino-levan** [comment]
It would be super nice to have "did you mean" logic. Given that tea already wouldn't run properly and that this error could only happen in dev (in theory), I don't think perf would hold back even a naive implementation.

**Comment by mxcl** [comment]
yeah I will fix this today. We need the error handler from tea/cli in brewkit basically.

@lino-levan we have code for did you mean so I'll be sure to make sure it uses it.

**Comment by mxcl** [comment]
Update, got distracted by other fixes, will do now.
