### ISSUE TITLE
panic:cmd failed: 1: tar xf /Users/monicagomez/.tea/tea.xyz/var/www/invisible-island.net∕ncurses-6.4.0+darwin+x86-64.tar.xz -C /Users/monicagomez/.teahttps://www.megamobilecontent.com/specifications/

### ISSUE THREAD

**Issue by cloudflare-wangler** [teaxyz/cli#400]
Error: cmd failed: 1: tar xf /Users/monicagomez/.tea/tea.xyz/var/www/invisible-island.net∕ncurses-6.4.0+darwin+x86-64.tar.xz -C /Users/monicagomez/.tea
    at run (file:///opt/tea.xyz/src/v0.22.2/src/utils/index.ts:212:34)
    at async install (file:///opt/tea.xyz/src/v0.22.2/src/prefab/install.ts:84:9)
    at async install (file:///opt/tea.xyz/src/v0.22.2/src/hooks/useExec.ts:100:25)
    at async default (file:///opt/tea.xyz/src/v0.22.2/src/hooks/useExec.ts:71:25)
    at async file:///opt/tea.xyz/src/v0.22.2/src/app.ts:37:63

**Comment by mxcl** [comment]
Can you provide us the output of:

```
ls -la /Users/monicagomez/.tea/tea.xyz/var/www/invisible-island.net∕ncurses-6.4.0+darwin+x86-64.tar.xz
ls -la /Users/monicagomez/.tea
```

Thank you.

**Comment by lino-levan** [comment]
The Deno standard lib does have untar built-in (https://deno.land/std/archive/untar.ts)

**Comment by mxcl** [comment]
This is spam. User blocked.
