### ISSUE TITLE
panic:Not a directory (os error 20)

### ISSUE THREAD

**Issue by sanchitram1** [teaxyz/cli#409]
```zsh
Error: Not a directory (os error 20), readdir '/Users/sanch/.tea/tea.xyz/var/pantries/.DS_Store'
    at async Object.[Symbol.asyncIterator] (internal:runtime/js/30_fs.js:132:16)
    at async Path.ls (file:///opt/tea.xyz/src-v0.24.6/src/vendor/Path.ts:166:26)
    at async ls (file:///opt/tea.xyz/src-v0.24.6/src/hooks/useSync.ts:144:31)
    at async file:///opt/tea.xyz/src-v0.24.6/src/hooks/useSync.ts:170:38
    at async lock (file:///opt/tea.xyz/src-v0.24.6/src/hooks/useSync.ts:52:16)
    at async update (file:///opt/tea.xyz/src-v0.24.6/src/hooks/useSync.ts:168:17)
    at async sync (file:///opt/tea.xyz/src-v0.24.6/src/app.sync.ts:6:5)
    at async file:///opt/tea.xyz/src-v0.24.6/src/app.ts:26:9
```

Going to that directory, I see `.DS_Store` but as a file, not a directory
```git 
sanch@Sanchits-MBP ~ % cd .tea/tea.xyz/var/pantries
sanch@Sanchits-MBP pantries % ls -lash
total 16
 0 drwxr-xr-x  4 sanch  staff   128B Feb 13 09:41 .
 0 drwxr-xr-x  6 sanch  staff   192B Feb  9 17:21 ..
16 -rw-r--r--@ 1 sanch  staff   6.0K Feb 13 09:41 .DS_Store
 0 drwxr-xr-x  5 sanch  staff   160B Feb 13 09:41 teaxyz
```

**Comment by sanchitram1** [comment]
Hard reset works like a charm :-)

```zsh
$ rm -rf tea
$ sh <(curl tea.xyz)
$ tea --sync
pantries sync’d ⎷
tea: empty pkg env
```
