### ISSUE TITLE
bug(dev): `run` task incorrectly invokes deno

### ISSUE THREAD

**Issue by vegerot** [teaxyz/cli#503]
The [README](https://github.com/teaxyz/cli/tree/main#hacking-on-teacli) mentions a bug in deno preventing tea being run with `deno run`

```sh
 deno task run foo
# ^^ runs the local checkout passing `foo` as an argument
# NOTE this doesn't currently work due to a bug in deno :(
```

Would you please explain more about this bug and provide a link to the Deno issue if there is one?

**Comment by mxcl** [comment]
I don’t think there's a bug report, we haven't checked. I know we should have made the report and for that we apologize.

You can try it in the checkout, eg:

```sh
$ cd tea/cli
$ deno run --version
error: unexpected argument '--version' found

  note: to pass '--version' as a value, use '-- --version'

Usage: deno run [OPTIONS] [SCRIPT_ARG]...

For more information, try '--help'.
```

The args are going to deno and not to tea itself. Doing it without the `task` runner doesn’t help:


```
$ deno run --unstable --allow-all src/app.ts --version
deno 1.32.3 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3

$ deno run --unstable --allow-all src/app.ts -- --version
error: unrecognized subcommand '--version'

Usage: deno [OPTIONS] [COMMAND]

For more information, try '--help'.
```

Though it's interesting the behavior varies based on if we use `--` or not.

**Comment by mxcl** [comment]
```json
{
  "tasks": {
    "run": "deno run --unstable --allow-all src/app.ts"
  }
}
```

**Comment by vegerot** [comment]
@mxcl thanks!  It's tracked in https://github.com/denoland/deno/issues/11547 and https://github.com/denoland/deno/issues/18631

**Comment by nayeemrmn** [comment]
@mxcl I can't reproduce it,
```ts
// temp.ts
console.log(Deno.args);

// deno.json
{
  "tasks": {
    "run": "deno run --unstable --allow-all temp.ts"
  }
}
```
```
$ deno task run --sync
Task run deno run --unstable --allow-all temp.ts "--sync"
[ "--sync" ]
```
Are you sure that error isn't coming from a subprocess launched by tea?

(I also tried your exact reproduction in this repo and got some other error:
```
$ deno task run --sync
Task run deno run --unstable --allow-all src/app.ts "--sync"
error: not-found: pantry (spilt-tea-009)
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
      const attachment = `${ctx.project}: ${ctx.cause.message}`
                                                      ^
    at msg (file:///home/nayeem/projects/deno/temp/cli/src/hooks/useErrorHandler.ts:80:55)
    at default (file:///home/nayeem/projects/deno/temp/cli/src/hooks/useErrorHandler.ts:38:21)
    at async file:///home/nayeem/projects/deno/temp/cli/src/app.ts:18:18
```
)

**Comment by mxcl** [comment]
K it does indeed look like this is `tea`’s fault because we use `tea` to run `deno`.

```
$ VERBOSE=1 deno task run --version
```

teaception! Sorry for the noise :(

**Comment by mxcl** [comment]
K yes we can reproduce this more directly:

```sh
$ VERBOSE=1 tea deno run --unstable --allow-all src/app.ts --version
tea 0.26.2+dev
{
  cwd: undefined,
  cmd: [ "deno", "run", "--unstable", "--allow-all", "src/app.ts", "--version" ],
  env: {
    VERSION: "0.26.2",
    SRCROOT: "/Users/mxcl/tea/cli",
    TEA_FILES: "/Users/mxcl/tea/cli/deno.jsonc:/Users/mxcl/tea/cli/README.md",
    DENO_NO_UPDATE_CHECK: "true",
    PATH: "/Users/mxcl/.tea/deno.land/v1.32.3/bin:/Users/mxcl/.local/bin:/usr/local/bin:/System/Cryptexes/App/u...",
    LDFLAGS: "-Wl,-rpath,/Users/mxcl/.tea",
    TEA_PREFIX: "/Users/mxcl/.tea",
    TEA_FORK_BOMB_PROTECTOR: "1"
  }
}
tea 0.26.2+dev
{
  cwd: undefined,
  cmd: [ "deno", "--version" ],
  env: {
    VERSION: "0.26.2",
    SRCROOT: "/Users/mxcl/tea/cli",
    TEA_FILES: "/Users/mxcl/tea/cli/deno.jsonc:/Users/mxcl/tea/cli/README.md",
    DENO_NO_UPDATE_CHECK: "true",
    PATH: "/Users/mxcl/.tea/deno.land/v1.32.3/bin:/Users/mxcl/.local/bin:/usr/local/bin:/System/Cryptexes/App/u...",
    LDFLAGS: "-Wl,-rpath,/Users/mxcl/.tea",
    TEA_PREFIX: "/Users/mxcl/.tea",
    TEA_FORK_BOMB_PROTECTOR: "2"
  }
}
deno 1.32.3 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
{ exit: { success: true, code: 0 } }
{ exit: { success: true, code: 0 } }
```

**Comment by mxcl** [comment]
So indeed, tea is executing itself to run `deno --version` rather than `--version`. Weird.

**Comment by mxcl** [comment]
we fixed this.
