### ISSUE TITLE
dua cli error when opening from gui

### ISSUE THREAD

**Issue by sanchitram1** [teaxyz/cli#570]
Installed `dua` from gui, and clicked on the Open In Terminal button, and got this error.  `dua` works fine when I use it on the cli though.

# Message
``sh
panic:end of the stream or a document separator is expected at line 5, column 19:     * @type { {action: () => void, nestingLevel: numb ...                       ^
``

# Attachment
``sh
YAMLError: end of the stream or a document separator is expected at line 5, column 19:
     * @type { {action: () => void, nestingLevel: numb ... 
                      ^
    at generateError (https://deno.land/std@0.182.0/yaml/_loader/loader.ts:88:12)
    at throwError (https://deno.land/std@0.182.0/yaml/_loader/loader.ts:91:11)
    at readDocument (https://deno.land/std@0.182.0/yaml/_loader/loader.ts:1079:16)
    at loadDocuments (https://deno.land/std@0.182.0/yaml/_loader/loader.ts:1103:9)
    at load (https://deno.land/std@0.182.0/yaml/_loader/loader.ts:1122:23)
    at parse (https://deno.land/std@0.182.0/yaml/parse.ts:13:12)
    at readYAMLFrontMatter (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/hooks/usePackageYAML.ts:95:38)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async usePackageYAMLFrontMatter (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/hooks/usePackageYAML.ts:75:18)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/hooks/useExec.ts:26:22)
``

**Comment by sanchitram1** [comment]
Happy to provide any more issues.  Since I started on cli, should I try and raise a bug on the gui side?
