### ISSUE TITLE
panic:No such file or directory (os error 2)

### ISSUE THREAD

**Issue by bahhhhh** [teaxyz/cli#578]
I get the following error when running `sh <(curl https://tea.xyz) +ffmpeg.org sh`:

```----------------------------------------------------->> attachment begin
NotFound: No such file or directory (os error 2)
    at spawnChildInner (ext:runtime/40_process.js:162:17)
    at spawnChild (ext:runtime/40_process.js:182:10)
    at Command.spawn (ext:runtime/40_process.js:439:12)
    at useRun (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/hooks/useRun.ts:34:12)
    at repl (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/app.exec.ts:80:15)
    at run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/app.main.ts:60:31)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/7eea0f48/src/app.ts:11:5
<<----------------------------------------------------- attachment end```

**Comment by mxcl** [comment]
Sorry for this bug @bahhhhh.

What is your shell? The error seems to be throwing in the section that is trying to use `fish`

**Comment by mxcl** [comment]
sorry @bahhhhh *how* did you try this? Setting your shell isn't a simple process.

Can you provide the commands you typed?

**Comment by mxcl** [comment]
Reopen if you can provide more info
