### ISSUE TITLE
panic:cmd failed: 128: /usr/bin/git fetch origin --force main:main

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#580]
this came from a user log when executing `.tea/tea.xyz/v*/bin/tea" --sync --env=false`
```
----------------------------------------------------->> attachment begin
Error: cmd failed: 128: /usr/bin/git fetch origin --force main:main
    at useRun (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useRun.ts:39:34)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async Promise.all (index 0)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:180:21
    at async lock (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:54:16)
    at async update (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:165:17)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/app.main.ts:24:9)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/app.ts:11:5
------------------------------------------------------------------------
{
  err: Error: cmd failed: 128: /usr/bin/git fetch origin --force main:main
    at useRun (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useRun.ts:39:34)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async Promise.all (index 0)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:180:21
    at async lock (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:54:16)
    at async update (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/hooks/useSync.ts:165:17)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/app.main.ts:24:9)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/fed00f19/src/app.ts:11:5
}
<<----------------------------------------------------- attachment end

    at ChildProcess.exithandler (node:child_process:409:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14) {
  code: 128,
  killed: false,
  signal: null,
  cmd: 'DEBUG=1 "/Users/username/.tea/tea.xyz/v*/bin/tea" --sync --env=false'
}

```

**Comment by mxcl** [comment]
what gui version? what cli version? pls always provide as much context as possible.

**Comment by mxcl** [comment]
closing due to requested info not being provided.
