### ISSUE TITLE
tea -E reports - "panic:couldn’t parse: .python-version"

### ISSUE THREAD

**Issue by metafeather** [teaxyz/cli#584]
```sh
❯ tea --version
tea 0.32.0
❯ uname -a
Darwin localhost 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
```

Running `tea -E` in my home directory:

```
Error: couldn’t parse: .python-version
    at supp (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/ea93ffc7/src/hooks/useVirtualEnv.ts:168:27)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async default (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/ea93ffc7/src/hooks/useVirtualEnv.ts:35:17)
    at async run (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/ea93ffc7/src/app.main.ts:31:30)
    at async file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/ea93ffc7/src/app.ts:11:5
```

The `~/.python-version` file:

```
3.11.2
home

```

I suspect it's because I use `pyenv` which puts the venv name in the file (which could be anything)?

```sh
❯ pyenv local
3.11.2
home
```

**Comment by jhheider** [comment]
very likely. if that's so, then we'd need to ignore that data. two questions:
1. if you remove the venv name line, does `tea -E` function correctly?
2. (open) is the a defined proper format for .python-version? i find few enough references on a quick search, and most of those think it just has the version string.

**Comment by mxcl** [comment]
patch fix released
