### ISSUE TITLE
teaxyz/infuser fails in Codefresh to resolve package graph "panic Invalid count value Infinity"

### ISSUE THREAD

**Issue by todaywasawesome** [teaxyz/cli#587]
Logs:

```
Pulling image teaxyz/infuser:latest
Digest: sha256:d4d59964b758b93182fc2e4156296a8a5878db4bc2806af982053fb0006e70d0
Status: Image is up to date for ghcr.io/teaxyz/infuser:latest
------------------------------
Executing command: tea node --eval \'console.log("Hello World!")\'
[38;5;238mtea:[39m resolving package graph
[G[InfinityA
[91mpanic[39m: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    [38;5;244mhttps://github.com/teaxyz/cli/issues/new?title=panic%3AInvalid+count+value%3A+Infinity[39m

----------------------------------------------------->> attachment begin
[38;5;244mRangeError: Invalid count value: Infinity
    at String.repeat (<anonymous>)
    at Function.eraseDown (https://deno.land/x/cliffy@v0.25.7/ansi/ansi_escapes.ts:100:23)
    at https://deno.land/x/cliffy@v0.25.7/ansi/tty.ts:59:96
    at Array.reduce (<anonymous>)
    at update (https://deno.land/x/cliffy@v0.25.7/ansi/tty.ts:59:24)
    at Function.tty (https://deno.land/x/cliffy@v0.25.7/ansi/tty.ts:17:13)
    at Logger.clear (file:///tmp/d0a92a7c/src/hooks/useLogger.ts:108:54)
    at install (file:///tmp/d0a92a7c/src/hooks/useExec.ts:125:12)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async default (file:///tmp/d0a92a7c/src/hooks/useExec.ts:82:38)[39m
<<----------------------------------------------------- attachment end
Reading environment variable exporting file contents.
Reading environment variable exporting file contents.
[31m[SYSTEM] 
 Message             Failed to run freestyle step: Run Tea Infuser                                                      
 Caused by           Container for step title: Run Tea Infuser, step type: freestyle, operation: Freestyle step. Failed 
                     with exit code: 128                                                                                
 Documentation Link  https://codefresh.io/docs/docs/codefresh-yaml/steps/freestyle/                                     
 Exit code           128                                                                                                
 Name                NonZeroExitCodeError                                                                               [0m
```

I checked to make sure it wasn't a dind thing by running it locally and it worked. 

I realize this may be more a Codefresh issue than a tea issue but would appreciate any guidance.

**Comment by mxcl** [comment]
sorry I didn't reply sooner, I missed this one. Thanks for the report! Found a divide by zero that can happen if the `tty` reports `0` for column size.
