### ISSUE TITLE
panic:FORK BOMB KILL SWITCH ACTIVATED

### ISSUE THREAD

**Issue by mikey-** [teaxyz/cli#590]
I had just installed neovim
```
tea +neovim.io
installed: ~/.tea/gnome.org/libxml2/v2.11.4
installed: ~/.tea/gnu.org/gettext/v0.21.1
installed: ~/.tea/neovim.io/v0.9.0

```
and I wanted to have `neovim` in my path, so I linked it to tea using the following function:
```shell
function tea-link () {
  ln -fns "${TEA_BIN}" "${TEA_LINK_DIR}/$1"
}
```
btw `TEA_LINK_DIR` and `TEA_BIN` have the following values (also `TEA_PREFIX` is in there too heh): 
```shell
TEA_LINK_DIR="${HOME}/tea/bin";
TEA_PREFIX="${HOME}/.tea";
TEA_BIN="${TEA_PREFIX}/tea.xyz/v*/bin/tea";
```

well, when I tried running `neovim --version` it blew up. 
```
Error: FORK BOMB KILL SWITCH ACTIVATED
    at default (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/907b0edd/src/app.exec.ts:14:28)
    at run (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/907b0edd/src/app.main.ts:43:31)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/907b0edd/src/app.ts:11:5
```
Then tea-cli told me to report it so here I am :)

**Comment by mikey-** [comment]
Oh snap I think it may have to do with having vim _and_ nvim installed (and linked) in this way :s

**Comment by mikey-** [comment]
another interesting thing to note is that the tea-gui doesn't think that neovim is installed  
<img width="807" alt="image" src="https://github.com/teaxyz/cli/assets/1870825/72d4912f-78dd-4c70-bf85-436e6c1b2e03">

**Comment by mikey-** [comment]
So, this is at least how I was able to install neovim
```shell
rm ~/tea/bin/nvim
rm ~/tea/bin/vim
rm ~/tea/bin/neovim
rm -rf "${TEA_PREFIX}/neovim.io"
rm -rf "${TEA_PREFIX}/vim.org"
tea nvim --version
installed: ~/.tea/neovim.io/v0.9.0
NVIM v0.9.0
...
```

**Comment by mxcl** [comment]
Thanks for the report!

The gui issue we'll solve in the next few releases.

The fork bomb is more concerning. Something must have been calling through to tea recursively. I don't fully understand the above in that context yet but will give it more thought.

**Comment by mxcl** [comment]
Yeah I can't fathom this out without some `ls -la` of the symlinks and what they symlink to. Sorry :/

**Comment by mxcl** [comment]
linux or mac?

**Comment by mikey-** [comment]
Apple M1 Pro with macOS 13.4 :)

**Comment by mikey-** [comment]
> Yeah I can't fathom this out without some `ls -la` of the symlinks and what they symlink to. Sorry :/

The links created in `$TEA_LINK_DIR` just point to the same thing: tea
```shell
ls -l $TEA_LINK_DIR
total 0
lrwxr-xr-x  1 mikey  people  41 18 May 12:00 bash -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 12:16 bun -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:58 curl -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 12:00 ipython -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:58 kubectl -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:59 kustomize -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 22 May 14:04 node -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 12:16 npm -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 24 May 03:07 nvim -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 12:00 pearl -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 12:00 pip -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:57 python -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:57 ruby -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 18 May 11:58 vhs -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
lrwxr-xr-x  1 mikey  people  41 24 May 03:20 vim -> /Users/mikey/.tea/tea.xyz/v*/bin/tea
```

**Comment by mxcl** [comment]
Thanks. Hmm, I'll have to consider what is happening and figure out a testcase and then solution.

**Comment by mxcl** [comment]
Closing as I believe this is fixed. Reopen if not.

**Comment by mikey-** [comment]
Thank you!
