### ISSUE TITLE
error: Uncaught (in promise) Error: bad-yaml

### ISSUE THREAD

**Issue by rokejulianlockhart** [teaxyz/cli#593]
I accidentally typed a `pwsh` command in `bash` via `code-insiders`, and

<blockquote>

```log
rokejulianlockhart@RQN6C6:~> Get-Command qmlformat
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~>
```

</blockquote>

appeared.

**Comment by mxcl** [comment]
We don’t know of any bad yamls currently, but `tea --sync` should fix whichever one you have that is bad, unless you edited the pantry yourself and have `TEA_PANTRY_PATH` set?

Either way, when the command not found handler runs we have to read the pantry to see if we offer that command, so that's what happened here. One of the pantry files is invalid apparently.

**Comment by rokejulianlockhart** [comment]
@mxcl,

> tea --sync should fix whichever one you have that is bad

```log
PS /home/rokejulianlockhart> bash
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~> tea --sync
pantries sync’d ⎷
tea: empty pkg env
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~>
```

> unless you edited the pantry yourself and have TEA_PANTRY_PATH set?

*I* haven't set `TEA_PANTRY_PATH`, and 

```log
PS /home/rokejulianlockhart> $Env:TEA_PANTRY_PATH                   
PS /home/rokejulianlockhart>
```

it doesn't appear to be. I haven't modified any locally cached manifests, either.

> One of the pantry files is invalid apparently.

Should this be transferred to https://github.com/teaxyz/pantry, then?

**Comment by mxcl** [comment]
what tea/cli you got? `tea --version`?

**Comment by rokejulianlockhart** [comment]
@mxcl,

```
PS /home/rokejulianlockhart> bash
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~> tea --sync
pantries sync’d ⎷
tea: empty pkg env
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~> cat /opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts
cat: /opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts: No such file or directory
rokejulianlockhart@RQN6C6:~> file /opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts
/opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts: cannot open `/opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts' (No such file or directory)
rokejulianlockhart@RQN6C6:~> exit
exit
PS /home/rokejulianlockhart> bash
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~> tea --version
tea 0.22.1
rokejulianlockhart@RQN6C6:~> tea --sync +tea.xyz
pantries sync’d ⎷
installed: ~/.tea/tea.xyz/v0.33.2
PATH=/home/rokejulianlockhart/.tea/tea.xyz/v0.33.2/bin:/home/rokejulianlockhart/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/snap/powershell-preview/140/opt/powershell:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/rokejulianlockhart/.tea/tea.xyz/v0.22.1/bin:/home/rokejulianlockhart/.local/bin:/usr/local/bin:/usr/bin:/bin:/home/rokejulianlockhart/.dotnet/tools:/snap/bin
rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~> sh <(curl tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13850  100 13850    0     0  22307      0 --:--:-- --:--:-- --:--:-- 22302
  
  the latest version of tea was already installed
  
  │ /home/rokejulianlockhart/.tea/tea.xyz/v0.33.2/bin/tea

rokejulianlockhart@RQN6C6:~> Get-Command
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.1/src/hooks/usePantry.ts:133:31)
rokejulianlockhart@RQN6C6:~>
```

**Comment by mxcl** [comment]
your tea/cli is very far behind somehow. what does `which tea` say? I'm guessing you have a tea binary that is in your `PATH` before the one the tea installer provides and we should somehow handle that.
