### ISSUE TITLE
Uncaught TypeError for clang

### ISSUE THREAD

**Issue by owittek** [teaxyz/cli#604]
Hey! I've tried to run a script and this error popped up. Unfortunately I can't give any more context since the script is not publicly available.

```console
/Users/oli/.tea/go.dev/v1.20.5/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
tea: installing go.dev, llvm.org
error: Uncaught TypeError: argv._.push is not a function
                argv._.push(flags.strings["_"] ?? !isNumber(arg) ? arg : Number(arg));
                       ^
    at parse (https://deno.land/std@0.177.0/flags/mod.ts:303:24)
    at getOptions (https://deno.land/std@0.177.0/node/internal_binding/node_options.ts:30:18)
    at getOptionsFromBinding (https://deno.land/std@0.177.0/node/internal/options.ts:26:37)
    at getOptionValue (https://deno.land/std@0.177.0/node/internal/options.ts:31:21)
    at https://deno.land/std@0.177.0/node/crypto.ts:21:20
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mxcl** [comment]
hmm do you know what command is running here?

The output is confusing. go is running it's link, which seems to cause _go to be installed_…? finally clang-16 errors out…!

**Comment by mxcl** [comment]
also super weird backtrace, none of our code and it *starts* in node/crypto…!

**Comment by owittek** [comment]
I ran a script that essentially does `go run . --start`. Inside of `main.go` it starts by checking if certain cli tools are installed on the machine. Perhaps this confuses tea?

**Comment by owittek** [comment]
> > it starts by checking if certain cli tools are installed on the machine. Perhaps this confuses tea?
> 
> scripts don’t get tea’s magic unless you manually source it. So probs not.
> 
> try setting `export DEBUG=1` and `set -x` in the script

The check for installed cli tools is already part of the `main.go` so that won't work. The function in the script responsible to call `main.go` is this:

```bash
    pushd $DIR
    go run . -start
    popd
```

so there's not a lot to debug on that side. The go script `exec.Command("the-command-to-check", "version").Run()` to check if it exists. Maybe this part triggers tea somehow due to the underlying implementation?

**Comment by mxcl** [comment]
`export DEBUG=1` and running the script will still give us more data as `tea` itself will output more.

**Comment by owittek** [comment]
> `export DEBUG=1` and running the script will still give us more data as `tea` itself will output more.

I did that and I didn't get any extra output. However I deleted `~/.tea` and reinstalled it before doing this as the issue prevented me from working.

**Comment by owittek** [comment]
I just wanted to see if I can reproduce the issue and ran `tea git` but I got this stacktrace instead:

```ts
{
  exit: [Object: null prototype] { success: false, code: 1, signal: null }
}
Error: cmd failed: 1:
    at useRun (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/45bf702e/src/hooks/useRun.ts:29:34)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/45bf702e/src/app.exec.ts:13:9)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/45bf702e/src/app.main.ts:59:25)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/45bf702e/src/app.ts:12:5 {
  code: 1,
  cmd: []
}
```

**Comment by mxcl** [comment]
this is expected `git` by itself returns exit code `1`.

**Comment by mxcl** [comment]
is the reported error still happening after your reinstall?

**Comment by owittek** [comment]
Doesn't seem like it.

**Comment by mxcl** [comment]
hmm… I hope this means we fixed it. We release a lot of point releases with fixes. Closing. Reopen if it happens again.

**Comment by mxcl** [comment]
I've seen this when clang is invoked via symlink.

Possibly too many args are passed for deno to handle or something.

**Comment by owittek** [comment]
Might be it, I'm using `ccache` which creates symlinks to itself for tools like clang.

**Comment by tekhnus** [comment]
Did some experimenting:
- I removed the symlinks from ~/.local/bin and invoked `~/.tea/.local/bin/clang hello.c`, it worked fine.
- After that, I added ~/.tea/.local/bin to PATH and invoked `clang hello.c`, it crashed:

```
% DEBUG=1 tea -vvv clang hello.c
resolving package graph
{
  hydrating: [
    {
      project: "llvm.org",
      path: ~/.tea/tea.xyz/var/pantry/projects/llvm.org/package.yml,
      constraint: *,
      shebang: [ "clang" ]
    }
  ]
{
  cmd: [ "clang", "hello.c" ],
  env: {
    PATH: "/Users/zahaaar/.tea/llvm.org/v16.0.5/bin:/Users/zahaaar/.local/share/go/bin:/Users/zahaaar/.cargo/bi"... 149 more characters,
    MANPATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/share/man:/Users/zahaaar/.tea/llvm.org/v16.0.5/share/man:/usr/s"... 8 more characters,
    PKG_CONFIG_PATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/lib/pkgconfig",
    LIBRARY_PATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/lib:/Users/zahaaar/.tea/llvm.org/v16.0.5/lib",
    LD_LIBRARY_PATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/lib:/Users/zahaaar/.tea/llvm.org/v16.0.5/lib",
    CPATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/include:/Users/zahaaar/.tea/llvm.org/v16.0.5/include",
    XDG_DATA_DIRS: "/Users/zahaaar/.tea/zlib.net/v1.2.13/share:/Users/zahaaar/.tea/llvm.org/v16.0.5/share",
    DYLD_FALLBACK_LIBRARY_PATH: "/Users/zahaaar/.tea/zlib.net/v1.2.13/lib:/Users/zahaaar/.tea/llvm.org/v16.0.5/lib",
    LDFLAGS: "-Wl,-rpath,/Users/zahaaar/.tea",
    TEA_PREFIX: "/Users/zahaaar/.tea",
    TEA_FORK_BOMB_PROTECTOR: "1"
  }
}
error: Uncaught TypeError: argv._.push is not a function
                argv._.push(flags.strings["_"] ?? !isNumber(arg) ? arg : Number(arg));
                       ^
    at parse (https://deno.land/std@0.177.0/flags/mod.ts:303:24)
    at getOptions (https://deno.land/std@0.177.0/node/internal_binding/node_options.ts:30:18)
    at getOptionsFromBinding (https://deno.land/std@0.177.0/node/internal/options.ts:26:37)
    at getOptionValue (https://deno.land/std@0.177.0/node/internal/options.ts:31:21)
    at https://deno.land/std@0.177.0/node/crypto.ts:21:20
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
{
  exit: [Object: null prototype] { success: false, code: 1, signal: null }
}
Error: cmd failed: 1: hello.c
    at useRun (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/hooks/useRun.ts:29:34)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.exec.ts:13:9)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.main.ts:59:25)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.ts:12:5 {
  code: 1,
  cmd: [ "hello.c" ]
}
% ls -la $(which clang)
lrwxr-xr-x  1 zahaaar  staff  3 Jun  9 12:48 /Users/zahaaar/.tea/.local/bin/clang -> tea
% ls -la $(which tea)
lrwxr-xr-x  1 zahaaar  staff  24 Jun  9 11:24 /Users/zahaaar/.tea/.local/bin/tea -> ../../tea.xyz/v*/bin/tea
```

**Comment by mxcl** [comment]
Closing with the hope is fixed in the latest release. reopen if not. i will also reopen if I find the same issue.

**Comment by tekhnus** [comment]
Confirming that clang toolchain now works fine for me, thanks!
