### ISSUE TITLE
Running tea with read-only permissions (panic:Permission denied (os error 13): remove '/opt/tea/tea.xyz/var/www/micro-editor.github.io-2.0.11+darwin+aarch64.tar.xz')

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#623]
I know you guys aren't really targeting this use case, but I hoping that it wouldn't be too hard to fix this. I have micro installed, but when I try to run it with an account that has read-only permissions on the tea folder (globally installed at /opt/tea), I get this error.

```
micro      
locking micro-editor.github.io=2.0.11

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3APermission+denied+(os+error+13)%3A+remove+'%2Fopt%2Ftea%2Ftea.xyz%2Fvar%2Fwww%2Fmicro-editor.github.io-2.0.11%2Bdarwin%2Baarch64.tar.xz'

----------------------------------------------------->> attachment begin
PermissionDenied: Permission denied (os error 13): remove '/opt/tea/tea.xyz/var/www/micro-editor.github.io-2.0.11+darwin+aarch64.tar.xz'
    at Object.removeSync (ext:deno_fs/30_fs.js:191:7)
    at Path.rm (https://deno.land/x/libtea@v0.7.0/src/utils/Path.ts:266:22)
    at install (https://deno.land/x/libtea@v0.7.0/src/plumbing/install.ts:113:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Promise.all (index 0)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/d50fe8a7/src/prefab/install.ts:63:27)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/d50fe8a7/src/prefab/setup.ts:84:38)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/d50fe8a7/src/app.main.ts:41:63)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/d50fe8a7/src/app.ts:20:5
<<----------------------------------------------------- attachment end
```

**Comment by magnusviri** [comment]
I should add, if I give that user write permission to /opt/tea, then it runs micro fine. If I remove the permissions, again, it gets that error.

**Comment by jhheider** [comment]
@magnusviri it looks like it's removing the downloaded tarball, in https://github.com/teaxyz/lib/blob/v0.7.0/src/plumbing/install.ts, so it thinks it is corrupted in some way. Is micro 2.0.11 already installed when you run this? And does adding write perms back to /opt/tea/tea.xyz/var (and all subs) fix it?

It's not clear why it should be removing the download, except that it does if any higher command throws. Since the .rm() is failing, its covering up the real error. Probably one of the lines like:
```typescript
const tmpdir = Path.mktemp({
      dir: tea_prefix.join(".local/tmp").join(pkg.project),
      prefix: `v${pkg.version}.`
      //NOTE ^^ inside tea prefix to avoid TMPDIR is on a different volume problems
    })
```
which is trying to make a tmpdir under /opt/tea/.local/tmp.

You're correct that we haven't built for the case of an unwritable prefix. But it's an interesting problem. You need both writable storage for any local work you do, and the immutable overlay for anything you need to protect.

**Comment by magnusviri** [comment]
I just deleted rm '/opt/tea/tea.xyz/var/www/micro-editor.github.io-2.0.11+darwin+aarch64.tar.xz' and tried it again. It is now trying to create a directory.

```
----------------------------------------------------->> attachment begin
Error: EACCES: permission denied, mkdir '/opt/tea/.local/tmp/micro-editor.github.io/v2.0.11.lG1lP0'
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:182:12)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1831:16)
    at mkdirSync (ext:deno_node/_fs/_fs_mkdir.ts:54:15)
    at mkdtempSync (ext:deno_node/_fs/_fs_mkdtemp.ts:28:5)
    at Function.mktemp (https://deno.land/x/libtea@v0.7.0/src/utils/Path.ts:202:20)
    at install (https://deno.land/x/libtea@v0.7.0/src/plumbing/install.ts:43:29)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Promise.all (index 0)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/d50fe8a7/src/prefab/install.ts:63:27)
<<----------------------------------------------------- attachment end
```

Maybe I should make .local/tmp world writable?

**Comment by magnusviri** [comment]
I made .local world writable and then this is the error.

```
locking micro-editor.github.io=2.0.11
error: http (spilt-tea-013)
Permission denied (os error 13): remove '/opt/tea/tea.xyz/var/www/https/dist.tea.xyz/959da778b8d1d1b9a2c0755e649fd129b5fb442a7e8f1c7a168537ff2a17b33a/mtime'
```

I made /opt/tea/tea.xyz/var/www world writable and then this is the error.

```
installing 100% 5.79 MiB/s 3.24/3 MiB

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Adest+already+exists.

----------------------------------------------------->> attachment begin
AlreadyExists: dest already exists.
    at https://deno.land/std@0.191.0/fs/move.ts:3:22
<<----------------------------------------------------- attachment end
```

Is it trying to reinstall it?

**Comment by mxcl** [comment]
IMO this scenario should work. It's weird it says “locking” it will only say that if it is trying to install. But you say it's already installed?

**Comment by mxcl** [comment]
I cannot reproduce, afaict this can only happen if the pkg is not installed.

I created a new tea installation, installed something, made it read only and then ran the tool without issue.

Reopen if you experience this again.
