### ISSUE TITLE
panic:invalid semver range: 1.15.4

### ISSUE THREAD

**Issue by levex** [teaxyz/cli#650]
My `tea.yaml`:

```
dependencies:
  elixir-lang.org: 1.15.4
  python.org: 3.10
```

The command: `tea -E`

The output:

```

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ainvalid+semver+range%3A+1.15.4

----------------------------------------------------->> attachment begin
Error: invalid semver range: 1.15.4
    at err (https://deno.land/x/libtea@v0.10.3/src/utils/semver.ts:118:29)
    at https://deno.land/x/libtea@v0.10.3/src/utils/semver.ts:202:23
    at Array.map (<anonymous>)
    at new Range (https://deno.land/x/libtea@v0.10.3/src/utils/semver.ts:119:56)
    at validatePackageRequirement (https://deno.land/x/libtea@v0.10.3/src/utils/hacks.ts:24:21)
    at file:///Users/builder/actions-runner/_work/cli/cli/src/hooks/useYAMLFrontMatter.ts:24:88
    at Array.compact (https://deno.land/x/libtea@v0.10.3/src/utils/misc.ts:40:30)
    at go (file:///Users/builder/actions-runner/_work/cli/cli/src/hooks/useYAMLFrontMatter.ts:24:55)
    at Object.getDeps (file:///Users/builder/actions-runner/_work/cli/cli/src/hooks/useYAMLFrontMatter.ts:18:16)
    at refineFrontMatter (file:///Users/builder/actions-runner/_work/cli/cli/src/hooks/useYAMLFrontMatter.ts:52:18)
<<------------------------------------------------------- attachment end
```

Seems eerily familiar to #272, might be just a good idea to add a simple error message.

**Comment by mxcl** [comment]
Adding an initial `^` will fix it for now, I'll apply a proper fix later today.

This is because I'm a stickler and enforced the range constructor to reject unmarked ranges, but that's just not human 🤦🏼

**Comment by mxcl** [comment]
> Yeah, it's a clear user error

I disagree! You did a very logical thing that we should have handled. Anyway fix coming up! Thanks so much for the report.

**Comment by levex** [comment]
Fair enough - thanks for the quick turnaround @mxcl! :-)

**Comment by mxcl** [comment]
v0.39.1 released last night had the fix.
