### ISSUE TITLE
Error `panic:invalid version: undefined` when running `tea -SE` with un-versioned `action.yml` file present (w. PR to fix it)

### ISSUE THREAD

**Issue by gaggle** [teaxyz/cli#690]
I thought I had a handle on what Tea did and the basics of how it worked, but then I hit this error on a new project:

```sh
$ tea -SE
pantries sync’d ⎷

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ainvalid+version%3A+undefined

----------------------------------------------------->> attachment begin
Error: invalid version: undefined
    at https://deno.land/x/libtea@v0.10.7/src/utils/semver.ts:44:27
    at Array.flatMap (<anonymous>)
    at new SemVer (https://deno.land/x/libtea@v0.10.7/src/utils/semver.ts:25:37)
    at https://deno.land/x/libtea@v0.10.7/src/utils/semver.ts:139:34
    at Array.map (<anonymous>)
    at new Range (https://deno.land/x/libtea@v0.10.7/src/utils/semver.ts:121:56)
    at supp (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/42af7169/src/hooks/useVirtualEnv.ts:219:29)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async default (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/42af7169/src/hooks/useVirtualEnv.ts:52:17)
    at async run (file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/42af7169/src/app.main.ts:43:30)
<<------------------------------------------------------- attachment end
```

I reran with verbose:
```sh
tea -vvv -SE
pantries sync’d ⎷
{
  tea: ".../.tea/tea.xyz/v0.39.6/bin/tea",
  deno: "1.36.0",
  v8: "11.6.189.12",
  typescript: "5.1.6"
}
.../action.yml
error: {
  "cause": {
    "string": ".../action.yml"
  }
}
```

The project has a tea.yml:
```yaml
dependencies:
  elixir-lang.org: =1.15.4
  erlang.org: =26.0.2
```

When running `tea -SE`, I anticipated Tea to read the `tea.yml` file and activate the specified dependencies.

Is the problem that Tea reads `action.yml` but can't find a version in `runs.using`? Because it wouldn't, because it [belongs to my GitHub Actions repository](https://github.com/gaggle/elixir_script/blob/main/action.yml) which uses Docker. Does Tea expect a version to be specified in an `action.yml` file?

**Comment by gaggle** [comment]
Indeed when I move `action.yml` away the problem goes away. 

https://github.com/teaxyz/cli/blob/080e540afe4c338dc7d07c55a25e6c40c61f9acd/src/hooks/useVirtualEnv.ts#L206-L213 

It looks like #L211 assumes there is always a version available?

**Comment by gaggle** [comment]
I pushed a PR in case it adds any value.
