### ISSUE TITLE
tea install fails if ~/.local/bin doesn't exist

### ISSUE THREAD

**Issue by vincentfiestada** [teaxyz/cli#757]
I'm not sure if it's intended behavior, but I would normally expect the package manager to create whatever directories it needs to install a package.

Running `tea install jq` fails on a fresh install.

```
× unexpected error No such file or directory (os error 2): writefile '/Users/vincent/.local/bin/jq'
│ NotFound: No such file or directory (os error 2): writefile '/Users/vincent/.local/bin/jq'
│     at writeFileSync (ext:deno_fs/30_fs.js:771:7)
│     at Object.writeTextFileSync (ext:deno_fs/30_fs.js:834:10)
│     at Path.write (https://deno.land/x/libtea@v0.13.0/src/utils/Path.ts:341:12)
│     at write (file:///Users/builder/actions-runner/_work/cli/cli/src/modes/install.ts:20:11)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/cli/cli/src/modes/install.ts:11:5)
│     at async default (file:///Users/builder/actions-runner/_work/cli/cli/src/app.ts:84:7)
│     at async file:///Users/builder/actions-runner/_work/cli/cli/entrypoint.ts:68:3
╰─➤ https://github.com/teaxyz/cli/issues/new
```

Creating the directory fixed the issue.

```
mkdir -p ~/.local/bin
```

**Comment by mxcl** [comment]
my bad, fix coming up

**Comment by mxcl** [comment]
notably we had to patch `npm` to do this lol
